const START_BOOKS_DATA = 'START_BOOKS_DATA';
const SET_BOOKS_DATA = 'SET_BOOKS_DATA';
const GET_BOOKS_DATA = 'GET_BOOKS_DATA';
const SET_FILTERS = 'SET_FILTERS';
const SET_API_ERROR = 'SET_API_ERROR';
const SET_LOAD_PAGE = 'SET_LOAD_PAGE';
const SET_NUMBER_OF_ITEMS_PER_PAGE = 'SET_NUMBER_OF_ITEMS_PER_PAGE';
export {
  SET_BOOKS_DATA,
  GET_BOOKS_DATA,
  START_BOOKS_DATA,
  SET_FILTERS,
  SET_API_ERROR,
  SET_LOAD_PAGE,
  SET_NUMBER_OF_ITEMS_PER_PAGE,
};
